//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingAssistance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class backupLoad
    {
        public int Id { get; set; }
        public string probill_number { get; set; }
        public string bol_number { get; set; }
        public Nullable<int> leg { get; set; }
        public Nullable<int> is_brokered { get; set; }
        public string truck_nember { get; set; }
        public Nullable<int> lane_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<System.DateTime> delete_data { get; set; }
        public Nullable<int> is_checked { get; set; }
    }
}
