//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingAssistance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FourkitesTrackingSentLeg
    {
        public int id { get; set; }
        public string order_id { get; set; }
        public int customer_id { get; set; }
        public string probill_number { get; set; }
        public int leg { get; set; }
        public string bol_number { get; set; }
        public string trip_number { get; set; }
        public string truck_number { get; set; }
        public string current_status { get; set; }
        public System.DateTime entry_time { get; set; }
        public byte is_brockered { get; set; }
        public int is_last_leg { get; set; }
        public Nullable<int> has_orignal_probill { get; set; }
        public string orignal_probill { get; set; }
        public Nullable<int> pickuplocation { get; set; }
        public Nullable<int> deliveredlocation { get; set; }
        public Nullable<int> lane_id { get; set; }
        public Nullable<System.DateTime> pickedup_time { get; set; }
        public Nullable<int> pingposition { get; set; }
    }
}
