//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingAssistance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FourKites_GPS_Sequencer
    {
        public int id { get; set; }
        public Nullable<int> CustomerLaneId { get; set; }
        public string CustomerLane { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> TimeOffset { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public string city { get; set; }
        public string state { get; set; }
    }
}
