//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingAssistance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FourKitesTrackingPendingLeg
    {
        public int id { get; set; }
        public string order_id { get; set; }
        public System.DateTime deliver_date { get; set; }
        public int customer_id { get; set; }
        public System.DateTime entry_date { get; set; }
        public string orignal_probill_number { get; set; }
        public Nullable<int> leg { get; set; }
        public string bol_number { get; set; }
        public Nullable<int> billing_group { get; set; }
        public string status { get; set; }
        public string orignal_trip_number { get; set; }
        public string orignal_truck_number { get; set; }
        public string orignal_com_type { get; set; }
        public Nullable<int> is_last_leg { get; set; }
        public Nullable<int> carrier_id { get; set; }
        public string assignment_id { get; set; }
        public string assignment_status { get; set; }
        public string assign_probill_number { get; set; }
        public string assign_trip_number { get; set; }
        public string assign_truck_number { get; set; }
        public string assign_com_type { get; set; }
    }
}
