//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingAssistance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FourKites_CustomerLane
    {
        public int id { get; set; }
        public string CustomerLane { get; set; }
        public string Customer { get; set; }
        public Nullable<int> PickLocation { get; set; }
        public Nullable<int> DelLocation { get; set; }
        public Nullable<int> TimeMin { get; set; }
        public Nullable<int> TimeMax { get; set; }
    }
}
