//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingAssistance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class probill
    {
        public int id { get; set; }
        public string pro_bill_id { get; set; }
        public string order_id { get; set; }
        public string originating_from { get; set; }
        public string final_destination { get; set; }
        public string hazardous { get; set; }
        public string un_code { get; set; }
        public string classification { get; set; }
        public string packing_group { get; set; }
        public Nullable<int> customs_broker { get; set; }
        public string temperature { get; set; }
        public string equipment { get; set; }
        public string container { get; set; }
        public string notes { get; set; }
        public Nullable<decimal> lbs { get; set; }
        public Nullable<decimal> kgs { get; set; }
        public Nullable<decimal> skids { get; set; }
        public Nullable<decimal> feet { get; set; }
        public Nullable<decimal> cube { get; set; }
        public Nullable<int> pick_up { get; set; }
        public Nullable<int> deliver { get; set; }
        public string pick_up_notes { get; set; }
        public string delivery_notes { get; set; }
        public Nullable<System.DateTime> pick_up_date { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public Nullable<System.DateTime> pick_up_time { get; set; }
        public Nullable<System.DateTime> delivery_time { get; set; }
        public Nullable<decimal> revenue { get; set; }
        public string manifest_id { get; set; }
        public string assignment_id { get; set; }
        public string status { get; set; }
        public Nullable<decimal> leg { get; set; }
        public Nullable<int> requested_pick_up { get; set; }
        public Nullable<int> requested_delivery { get; set; }
        public Nullable<System.DateTime> requested_pick_up_date { get; set; }
        public Nullable<System.DateTime> requested_pick_up_time { get; set; }
        public Nullable<System.DateTime> requested_delivery_date { get; set; }
        public Nullable<System.DateTime> requested_delivery_time { get; set; }
        public Nullable<decimal> pieces { get; set; }
        public Nullable<decimal> units { get; set; }
        public Nullable<decimal> cwt { get; set; }
        public Nullable<decimal> ft_board { get; set; }
        public Nullable<decimal> truck_load { get; set; }
        public Nullable<decimal> metric_tonne { get; set; }
        public Nullable<decimal> imperial_ton { get; set; }
        public Nullable<decimal> imperial_gallon { get; set; }
        public Nullable<decimal> us_gallon { get; set; }
        public Nullable<decimal> litres { get; set; }
        public Nullable<decimal> hours { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> length { get; set; }
        public string whl_type { get; set; }
        public Nullable<decimal> weight_cube { get; set; }
        public string terminal { get; set; }
        public string division { get; set; }
        public string commodity { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<System.DateTime> picked_up_on { get; set; }
        public Nullable<System.DateTime> picked_up_at { get; set; }
        public Nullable<System.DateTime> delivered_on { get; set; }
        public Nullable<System.DateTime> delivered_at { get; set; }
        public Nullable<decimal> percent_of_order { get; set; }
        public Nullable<decimal> percent_of_pro { get; set; }
        public Nullable<decimal> percent_of_assignment { get; set; }
        public string trip { get; set; }
        public Nullable<int> assigned_truck { get; set; }
        public Nullable<int> assigned_trailer { get; set; }
        public Nullable<int> assigned_container { get; set; }
        public string dispatched { get; set; }
        public string pro_leg { get; set; }
        public string to_be_brokered { get; set; }
        public Nullable<decimal> percent_of_trip { get; set; }
        public Nullable<decimal> payroll_percent { get; set; }
        public string cancelled { get; set; }
        public Nullable<int> history_truck { get; set; }
        public Nullable<int> history_trailer { get; set; }
        public Nullable<int> history_container { get; set; }
        public Nullable<System.DateTime> date_dispatched { get; set; }
        public Nullable<System.DateTime> time_dispatched { get; set; }
        public string user_dispatched { get; set; }
        public string comm_status { get; set; }
        public string dispatched_by { get; set; }
        public Nullable<System.DateTime> dispatched_date { get; set; }
        public Nullable<System.DateTime> dispatched_time { get; set; }
        public string bill_of_lading { get; set; }
        public Nullable<int> location { get; set; }
        public string location_code { get; set; }
        public Nullable<decimal> seats { get; set; }
        public string compartment { get; set; }
        public string preferred_carrier { get; set; }
        public Nullable<int> delivered_by_3rd { get; set; }
        public string hazmat_shipping_name { get; set; }
        public string hazmat_erp { get; set; }
        public Nullable<decimal> declared_value { get; set; }
        public Nullable<decimal> cod_amount { get; set; }
        public string cod_currency { get; set; }
        public string cod_payable_by { get; set; }
        public string cod_remit_to { get; set; }
        public string declared_value_currency { get; set; }
        public string zero_percent { get; set; }
        public Nullable<int> driver { get; set; }
        public Nullable<int> trip_type { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public string external_id { get; set; }
        public string commodity_description { get; set; }
        public string truck_class { get; set; }
        public string trailer_class { get; set; }
        public string pending_reason_code { get; set; }
        public string external_id_sender { get; set; }
        public Nullable<int> shipped_from { get; set; }
        public Nullable<int> shipped_to { get; set; }
        public Nullable<System.DateTime> shipped_from_date { get; set; }
        public Nullable<System.DateTime> shipped_to_date { get; set; }
        public Nullable<decimal> excess_amount { get; set; }
        public string locked { get; set; }
        public string locked_by { get; set; }
        public Nullable<System.DateTime> locked_on { get; set; }
        public string user_column_1 { get; set; }
        public string user_column_2 { get; set; }
        public Nullable<decimal> default_percent_of_order { get; set; }
        public Nullable<decimal> default_percent_of_probill { get; set; }
        public string last_leg { get; set; }
        public string fda { get; set; }
        public string pieces_uom { get; set; }
        public string ace_status { get; set; }
        public Nullable<int> ace_message { get; set; }
        public Nullable<decimal> estimated_cost { get; set; }
        public string on_hold { get; set; }
        public Nullable<int> cancel_notes_id { get; set; }
        public Nullable<decimal> default_percent_of_leg { get; set; }
        public string image_scanned { get; set; }
        public string haz_subclass_1 { get; set; }
        public string haz_subclass_2 { get; set; }
        public string haz_subclass_3 { get; set; }
        public string haz_nos_applicable { get; set; }
        public string haz_technical_name { get; set; }
        public Nullable<int> haz_emergency_contact { get; set; }
        public string erap_contact_number { get; set; }
        public Nullable<int> commodity_owner { get; set; }
        public Nullable<int> load_opt_batch_id { get; set; }
        public string temp_control { get; set; }
        public Nullable<System.DateTime> modified_time { get; set; }
        public string consolidation_no { get; set; }
        public Nullable<decimal> dedicated_leg_value { get; set; }
        public string waiting_for_pod { get; set; }
        public Nullable<decimal> revenue_leg { get; set; }
        public Nullable<decimal> revenue_pro { get; set; }
        public Nullable<decimal> expense_pro { get; set; }
        public Nullable<decimal> expense_leg { get; set; }
        public Nullable<decimal> cost_expense_leg { get; set; }
        public Nullable<decimal> cost_leg { get; set; }
        public Nullable<System.DateTime> original_req_pickup_date { get; set; }
        public Nullable<System.DateTime> original_req_pickup_time { get; set; }
        public Nullable<System.DateTime> original_req_delivery_date { get; set; }
        public Nullable<System.DateTime> original_req_delivery_time { get; set; }
        public string load_posted { get; set; }
        public string aci_status { get; set; }
        public Nullable<int> aci_message { get; set; }
        public string image_entity_id { get; set; }
        public string commodity_po_number { get; set; }
        public string revenue_distribution_notes { get; set; }
    }
}
