//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingAssistance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingBackup
    {
        public int id { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public string probill { get; set; }
        public string path { get; set; }
        public string current_status { get; set; }
    }
}
